### ISSUE TITLE
Upgrade to etcd v3.4.26 to fix vulnerabilities from go runtime

### ISSUE THREAD

**Issue by lizzzcai** [gardener/etcd-custom-image#33]
**What would you like to be added**:

Hi colleagues, the current etcd image (`eu.gcr.io/gardener-project/gardener/etcd:v3.4.13-bootstrap-10`) maintained by gardener has around `140+` vulnerabilities (mainly from go runtime).
 
I check the official etcd [v3.4.26](https://github.com/etcd-io/etcd/releases/tag/v3.4.26) is using the latest go runtime to fix all these vulnerabilities, is it possible to upgrade to this version?

BTW I also saw this [issue](https://github.com/gardener/etcd-custom-image/issues/16) which slowly upgrade to `v3.6.x` to avoid vulnerabilities from base image, is there any timeline? 

**Why is this needed**:

fix vulnerabilities from go runtime for security compliance.

**Comment by unmarshall** [comment]
This repository will soon be replaced by https://github.com/gardener/etcd-wrapper (PR is under review). At the moment we have preserved the same etcd version (3.14.3) but we already have a backlog item to move to the latest version of etcd (https://github.com/gardener/etcd-druid/issues/445). Since there are a lot of breaking changes between 3.14.3 and the latest version of etcd we will need some time to test and identify + make changes due to API changes.

**Comment by unmarshall** [comment]
[etcd-wrapper](https://github.com/gardener/etcd-wrapper/releases/tag/v0.1.0) has now been released. This currently uses v3.4.26 version of etcd. It will soon be integrated with etcd-druid as a de-facto etcd container.

**Comment by shreyas-s-rao** [comment]
This issue can now be closed since druid release v0.19.0 will use [etcd-wrapper](https://github.com/gardener/etcd-wrapper), running etcd `v3.4.26`. @lizzzcai please watch [etcd-druid](https://github.com/gardener/etcd-druid) for the v0.19.0 release.
/close
